#!/bin/sh
RED="\e[31m"
GREEN="\e[32m"
NC="\e[0m"

all_files=()

while read -r file; do
  file="$(printf "${file}")"     # convert unicode numbers into carachters
  file="$(eval "echo ${file}")"  # remove quotation if exists
  echo "${file}" |
    grep -E '.(c|cc|cpp|hpp|h)$' >& /dev/null &&
    all_files+=(${file})
done < <(git diff --cached --diff-filter=d --name-only)
# echo "${all_files[@]}"; exit 0

if (( ${#all_files} )); then
  clang-format -i "${all_files[@]}"
  formatter_exit_code=$?
fi

git add -f "${all_files[@]}"

if [ $formatter_exit_code -ne 0 ]; then
  echo -e "${RED}❌ error:${NC} ccls-format failed with code ${formatter_exit_code}, ( ͡ಥ ͜ʖ ͡ಥ)"
  exit 1
else
  echo -e "${GREEN}✔ formatter succeeded:${NC} Files are formatted [̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]"
  exit 0
fi
